files:
  - source: /res/values/custom_strings.xml
    translation: /res/values-%android_code%/evolution_strings.xml
  - source: /res/values/custom_plurals.xml
    translation: /res/values-%android_code%/evolution_plurals.xml
