files:
  - source: /res/values/custom_strings.xml
    translation: /res/values-%android_code%/custom_strings.xml
  - source: /res/values/custom_plurals.xml
    translation: /res/values-%android_code%/custom_plurals.xml
  - source: /res/values/projekt_strings.xml
    translation: /res/values-%android_code%/projekt_strings.xml
